version: "3"
services:
  itourbot-api:
    image: itourbot-api:latest
    container_name: itourbot-api
    build: .
    command: yarn dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - itourbot
    restart: always
  itourbot-redis:
    image: redis:latest
    container_name: itourbot-redis
    ports:
      - "6379:6379"
    networks:
      - itourbot
    restart: always

networks:
  itourbot:
    external: true